//	addcomponent
export const RECEIVE_ADD_COMPONENT = 'RECEIVE_ADD_COMPONENT'
export const RECEIVE_PUSH_COMPONENT = 'RECEIVE_PUSH_COMPONENT'
export const RECEIVE_DELETE_COMPONENT = 'RECEIVE_DELETE_COMPONENT'

//	savetemplate
export const RECEIVE_SAVE_TEMPLATE = 'RECEIVE_SAVE_TEMPLATE'

//	savedtemplate
export const RECEIVE_SAVED_TEMPLATE = 'RECEIVE_SAVED_TEMPLATE'
export const RECEIVE_ADD_TAB = 'RECEIVE_ADD_TAB' // 添加标签信息
export const RECEIVE_CHANGE_TAB = 'RECEIVE_CHANGE_TAB' // 修改标签信息
export const RECEIVE_DELETE_TAB = 'RECEIVE_DELETE_TAB' // 删除标签信息
export const RECEIVE_CHANGE_TABSTATUS = 'RECEIVE_CHANGE_TABSTATUS' // 修改页签状态
export const RECEIVE_RESET_DATA = 'RECEIVE_RESET_DATA' // 重置样式以及数据
export const DELETE_SALE_TABS = 'DELETE_SALE_TABS' // 删除销售属性多模式页签
export const SET_SALE_TABS = 'SET_SALE_TABS' // 设置销售属性多模式页签
//	addproduct
export const RECEIVE_ADD_PRODUCT = 'RECEIVE_ADD_PRODUCT'
export const RECEIVE_NEWADD_PRODUCT = 'RECEIVE_NEWADD_PRODUCT'
export const RECEIVE_ADD_LINKAGE = 'RECEIVE_ADD_LINKAGE'
export const RECEIVE_ADD_LINKAGE_SEARCH = 'RECEIVE_ADD_LINKAGE_SEARCH'
export const RECEIVE_PRODUCT_RESULT = 'RECEIVE_PRODUCT_RESULT'
export const RECEIVE_ORGANIZE_SALE_DATA = 'RECEIVE_ORGANIZE_SALE_DATA'
export const RECEIVE_FETCH_COMMODITY_DATA = 'RECEIVE_FETCH_COMMODITY_DATA'
export const RECEIVE_FETCH_WARE_DATA = 'RECEIVE_FETCH_WARE_DATA'
export const RECEIVE_MODIFY_PRODUCT = 'RECEIVE_MODIFY_PRODUCT'
export const RECEIVE_CHANGE_DIM_DATA = 'RECEIVE_CHANGE_DIM_DATA'
export const RECEIVE_DELETE_SALESATTRS = 'RECEIVE_DELETE_SALESATTRS'
export const RECEIVE_SALEPROPERTY_EXTEND = 'RECEIVE_SALEPROPERTY_EXTEND'
export const RECEIVE_CHANGE_ERROR_MSG = 'RECEIVE_CHANGE_ERROR_MSG'
// export const RECEIVE_UPLOAD_IMAGE = 'RECEIVE_UPLOAD_IMAGE'
export const RECEIVE_REMOVE_IMAGE = 'RECEIVE_REMOVE_IMAGE'
export const RECEIVE_COMMIT_WARE_DATA = 'RECEIVE_COMMIT_WARE_DATA'
export const RECEIVE_CHANGE_STATUS = 'RECEIVE_CHANGE_STATUS'
export const RECEIVE_LINKAGE_INIT = 'RECEIVE_LINKAGE_INIT'
export const RECEIVE_SAVE_RICHTEXT = 'RECEIVE_SAVE_RICHTEXT'
export const RECEIVE_SELECT_RICHTEXT = 'RECEIVE_SELECT_RICHTEXT'
export const RECEIVE_CONCAT_NAME = 'RECEIVE_CONCAT_NAME'
export const RECEIVE_CHANGE_CALENDAR_DATA = 'RECEIVE_CHANGE_CALENDAR_DATA'
export const RECEIVE_BIG_DATA = 'RECEIVE_BIG_DATA'
export const RECEIVE_DELETE_CALENDAR_DATA = 'RECEIVE_DELETE_CALENDAR_DATA'
export const RECEIVE_SALE_VALIDATE_MSG = 'RECEIVE_SALE_VALIDATE_MSG'
export const RECEIVE_SELECT_BIG_DATA = 'RECEIVE_SELECT_BIG_DATA'
export const RECEIVE_CHANGE_CALENDAR_BASE_DATA = 'RECEIVE_CHANGE_CALENDAR_BASE_DATA'
export const ORGANIZE_SALE_RECORDS_DATA = 'ORGANIZE_SALE_RECORDS_DATA'
export const RECEIVE_SHOP_CATEGORY = 'RECEIVE_SHOP_CATEGORY'
export const ORGANIZE_SHOP_CATEGORY = 'ORGANIZE_SHOP_CATEGORY'
export const RECEIVE_FETCH_CATE = 'RECEIVE_FETCH_CATE'
export const RECEIVE_CHOOSE_IMAGES = 'RECEIVE_CHOOSE_IMAGES'
